component                           = page_object blank_lines
                                    / action_c  blank_lines
                                    / region blank_lines
                                    / action_d blank_lines
                                    / action_e blank_lines
                                    / process blank_lines
                                    / button blank_lines
                                    / computation_a blank_lines
                                    / facet blank_lines
                                    / column_b blank_lines
                                    / column_f blank_lines