page_item                           = indent "pageItem" (required_ws component_id)? ws "(" line_end page_item_body_line* indent ")" line_end
page_item_body_line                 = page_item_direct_property_line
                                    / page_item_group_block
                                    / blank_lines

page_item_direct_property_line      = indent page_item_direct_property line_end
page_item_direct_property           = "name" ":" ws string_like_value
                                    / "type" ":" ws string_like_value

page_item_group_block               = page_item_label
                                    / page_item_settings
                                    / page_item_layout
                                    / page_item_appearance
                                    / page_item_validation
                                    / page_item_advanced
                                    / page_item_security
                                    / page_item_session_state
                                    / page_item_lov
                                    / page_item_default

page_item_label                     = indent "label" ws "{" line_end page_item_label_property_line* indent "}" line_end
page_item_label_property_line       = indent page_item_label_property line_end
page_item_label_property            = "label" ":" ws string_like_value
                                    / "alignment" ":" ws ( "above" / "below" / "center" / "centerBottom" / "centerCenter" / "centerTop" / "left" / "leftBottom" / "leftCenter" / "leftTop" / "right" / "rightBottom" / "rightCenter" / "rightTop" )
                                    / "tableCellAttributes" ":" ws array_of_string_like_value

page_item_settings                  = indent "settings" ws "{" line_end page_item_settings_property_line* indent "}" line_end
page_item_settings_property_line    = indent page_item_settings_property line_end
page_item_settings_property         = "trimSpaces" ":" ws ( "none" / "something-else" )
                                    / "dummy" ":" ws string_like_value


page_item_layout                    = indent "layout" ws "{" line_end page_item_layout_property_line* indent "}" line_end
page_item_layout_property_line      = indent page_item_layout_property line_end
page_item_layout_property           = "sequence" ":" ws number
                                    / "region" ":" ws reference
                                    / "slot" ":" ws string_like_value
                                    / "alignment" ":" ws ( "center" / "centerBottom" / "centerCenter" / "centerTop" / "left" / "leftBottom" / "leftCenter" / "leftTop" / "right" / "rightBottom" / "rightCenter" / "rightTop" )
                                    / "startNewLayout" ":" ws boolean
                                    / "startNewRow" ":" ws boolean
                                    / "rowCssClasses" ":" ws array_of_string_like_value
                                    / "column" ":" ws string_like_value
                                    / "newColumn" ":" ws boolean
                                    / "columnSpan" ":" ws string_like_value
                                    / "rowSpan" ":" ws number
                                    / "labelColumnSpan" ":" ws string_like_value
                                    / "columnCssClasses" ":" ws array_of_string_like_value
                                    / "columnAttributes" ":" ws array_of_string_like_value

page_item_appearance                = indent "appearance" ws "{" line_end page_item_appearance_property_line* indent "}" line_end
page_item_appearance_property_line  = indent page_item_appearance_property line_end
page_item_appearance_property       = "template" ":" ws reference
                                    / "templateOptions" ":" ws ( array_of_string_like_value / string_like_value )
                                    / "cssClasses" ":" ws ( array_of_string_like_value / string_like_value )
                                    / "icon" ":" ws string_like_value
                                    / "formatMask" ":" ws string_like_value
                                    / "valuePlaceholder" ":" ws string_like_value
                                    / "width" ":" ws number
                                    / "height" ":" ws number

page_item_validation                = indent "validation" ws "{" line_end page_item_validation_property_line* indent "}" line_end
page_item_validation_property_line  = indent page_item_validation_property line_end
page_item_validation_property       = "valueRequired" ":" ws boolean
                                    / "maxLength" ":" ws number

page_item_advanced                  = indent "advanced" ws "{" line_end page_item_advanced_property_line* indent "}" line_end
page_item_advanced_property_line    = indent page_item_advanced_property line_end
page_item_advanced_property         = "cssClasses" ":" ws array_of_string_like_value
                                    / "customAttributes" ":" ws string_like_value
                                    / "optionHtmlAttributes" ":" ws array_of_string_like_value
                                    / "preText" ":" ws ( string_like_value / multiline_string )
                                    / "postText" ":" ws ( string_like_value / multiline_string )
                                    / "warnOnUnsavedChanges" ":" ws ( "ignore" )
                                    / "initJavaScriptFunction" ":" ws (string_like_value / multiline_string )

page_item_session_state             = indent "sessionState" ws "{" line_end page_item_session_state_property_line* indent "}" line_end
page_item_session_state_property_line  = indent page_item_session_state_property line_end
page_item_session_state_property       = "dataType" ":" ws ( "varchar2" / "clob" / "boolean" / "number" )
                                    / "storage" ":" ws ( "request" / "session" / "user" )

page_item_security                  = indent "security" ws "{" line_end page_item_security_property_line* indent "}" line_end
page_item_security_property_line    = indent page_item_security_property line_end
page_item_security_property         = "authorizationScheme" ":" ws reference
                                    / "sessionStateProtection" ":" ws ( "unrestricted" / "checksumRequiredAppLevel" / "checksumRequiredUserLevel" / "checksumRequiredSessionLevel" / "restricted" )
                                    / "encryptSessionState" ":" ws boolean
                                    / "escapeSpecialChars" ":" ws boolean
                                    / "restrictedChars" ":" ws ( "alphanumWithSpace" / "webSafe" / "noSpecialChar" / "noSpecialCharNoNewline" / "workspaceSchema" / "workspaceUserSchema" / "workspaceUserSchemaId" )

page_item_lov                       = indent "lov" ws "{" line_end page_item_lov_property_line* indent "}" line_end
page_item_lov_property_line         = indent page_item_lov_property line_end
page_item_lov_property              = "type" ":" ws ( "sharedComponent" / "sqlQuery" / "staticValues" / "functionBody" )
                                    / "lov" ":" ws reference
                                    / "sqlQuery" ":" ws code_block
                                    / "staticValues" ":" ws multiline_string
                                    / "language" ":" ws ( "plsql" / "javaScript-mle" )
                                    / "plsqlFunctionBody" ":" ws code_block
                                    / "javaScriptFunctionBody" ":" ws code_block
                                    / "displayExtraValues" ":" ws boolean
                                    / "displayNullValue" ":" ws boolean
                                    / "nullDisplayValue" ":" ws string_like_value
                                    / "nullReturnValue" ":" ws string_like_value

page_item_default                   = indent "default" ws "{" line_end page_item_default_property_line* indent "}" line_end
page_item_default_property_line     = indent page_item_default_property line_end
page_item_default_property          = "type" ":" ws ( "static" / "item" / "sqlQuerySingleValue" 
                                        / "sqlQueryMultipleValues" / "expression" / "functionBody" / "sequence" )
                                    / "staticValue" ":" ws code_block
                                    / "item" ":" ws string_like_value
                                    / "sqlQuerySingleValue" ":" ws multiline_string
                                    / "sqlQueryMultipleValues" ":" ws multiline_string
                                    / "language" ":" ws ( "sql" / "plsql" / "javaScript-mle" )
                                    / "sqlExpression" ":" ws multiline_string
                                    / "plsqlExpression" ":" ws multiline_string
                                    / "javaScriptExpression" ":" ws multiline_string
                                    / "plsqlFunctionBody" ":" ws multiline_string
                                    / "javaScriptFunctionBody" ":" ws multiline_string
                                    / "sequence" ":" ws string_like_value
